@php($value = fn ($field, $default = '') => old($field, $noticeItem?->{$field} ?? $default))
<div class="ltd-form-card__body">
    @if($noticeItem?->source_url)<div class="alert alert-info"><strong>Official source:</strong> {{ $noticeItem->source_name }}<br><a href="{{ $noticeItem->source_url }}" target="_blank" rel="noopener noreferrer">Open original government notice <i class="fas fa-external-link-alt ml-1"></i></a><div class="small mt-1">Review the source and complete both language fields before publishing.</div></div>@endif
    <section class="ltd-form-section"><h3 class="ltd-form-section__title">English</h3><div class="form-group"><label class="ltd-field-label" for="title">Title <span class="ltd-required">*</span></label><input id="title" name="title" value="{{ $value('title') }}" maxlength="255" class="form-control @error('title') is-invalid @enderror" required>@error('title')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><label class="ltd-field-label" for="description">Description <span class="ltd-required">*</span></label><textarea id="description" name="description" rows="4" maxlength="1000" class="form-control @error('description') is-invalid @enderror" required>{{ $value('description') }}</textarea>@error('description')<div class="invalid-feedback">{{ $message }}</div>@enderror</section>
    <section class="ltd-form-section"><h3 class="ltd-form-section__title">Nepali</h3><div class="form-group"><label class="ltd-field-label" for="nepaliTitle">शीर्षक <span class="ltd-required">*</span></label><input id="nepaliTitle" name="nepaliTitle" value="{{ $value('nepaliTitle') }}" maxlength="255" lang="ne" class="form-control @error('nepaliTitle') is-invalid @enderror" required>@error('nepaliTitle')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><label class="ltd-field-label" for="nepaliDescription">विवरण <span class="ltd-required">*</span></label><textarea id="nepaliDescription" name="nepaliDescription" rows="4" maxlength="1000" lang="ne" class="form-control @error('nepaliDescription') is-invalid @enderror" required>{{ $value('nepaliDescription') }}</textarea>@error('nepaliDescription')<div class="invalid-feedback">{{ $message }}</div>@enderror</section>
    <section class="ltd-form-section"><h3 class="ltd-form-section__title">Publishing</h3><div class="row">
        <div class="col-md-4 form-group"><label class="ltd-field-label" for="status">Status <span class="ltd-required">*</span></label><select id="status" name="status" class="form-control @error('status') is-invalid @enderror" required>@foreach(['Draft','Published','Archived'] as $status)<option value="{{ $status }}" {{ $value('status', 'Draft') === $status ? 'selected' : '' }}>{{ $status }}</option>@endforeach</select>@error('status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-4 form-group"><label class="ltd-field-label" for="publish_at">Publish date <span class="text-muted">(optional)</span></label><input id="publish_at" type="datetime-local" name="publish_at" value="{{ old('publish_at', $noticeItem?->publish_at?->format('Y-m-d\TH:i')) }}" class="form-control @error('publish_at') is-invalid @enderror">@error('publish_at')<div class="invalid-feedback">{{ $message }}</div>@enderror<small class="form-text text-muted">Leave empty to publish immediately.</small></div>
        <div class="col-md-4 form-group"><label class="ltd-field-label" for="expires_at">Expiration date <span class="text-muted">(optional)</span></label><input id="expires_at" type="datetime-local" name="expires_at" value="{{ old('expires_at', $noticeItem?->expires_at?->format('Y-m-d\TH:i')) }}" class="form-control @error('expires_at') is-invalid @enderror">@error('expires_at')<div class="invalid-feedback">{{ $message }}</div>@enderror<small class="form-text text-muted">Expired notices disappear from the learner app.</small></div>
    </div><label class="ltd-field-label" for="link">Related URL <span class="text-muted">(optional)</span></label><input id="link" type="url" name="link" value="{{ $value('link') }}" maxlength="2048" class="form-control @error('link') is-invalid @enderror" placeholder="https://...">@error('link')<div class="invalid-feedback">{{ $message }}</div>@enderror</section>
</div>
