@extends('admin.layout.master')
@section('title', 'Add Notice')
@section('content')
<div class="ltd-page-header"><div><span class="ltd-page-header__eyebrow">Announcements</span><h1>Add Notice</h1></div></div>
<div class="ltd-form-shell"><form class="ltd-form-card" action="{{ route('insertNotice') }}" method="POST" data-add-form>@csrf
    <div class="ltd-form-card__intro"><i class="fas fa-bullhorn"></i><div><h2>Publish a bilingual notice</h2><p>Keep the English and Nepali versions equivalent and include a source link when useful.</p></div></div>
    <div class="ltd-form-card__body">
        <section class="ltd-form-section"><h3 class="ltd-form-section__title">English</h3><div class="form-group"><label class="ltd-field-label" for="title">Title <span class="ltd-required">*</span></label><input id="title" name="title" value="{{ old('title') }}" maxlength="255" class="form-control @error('title') is-invalid @enderror" required>@error('title')<div class="invalid-feedback">{{ $message }}</div>@enderror></div><label class="ltd-field-label" for="description">Description <span class="ltd-required">*</span></label><textarea id="description" name="description" rows="4" maxlength="1000" class="form-control @error('description') is-invalid @enderror" required>{{ old('description') }}</textarea>@error('description')<div class="invalid-feedback">{{ $message }}</div>@enderror></section>
        <section class="ltd-form-section"><h3 class="ltd-form-section__title">Nepali</h3><div class="form-group"><label class="ltd-field-label" for="nepaliTitle">शीर्षक <span class="ltd-required">*</span></label><input id="nepaliTitle" name="nepaliTitle" value="{{ old('nepaliTitle') }}" maxlength="255" lang="ne" class="form-control @error('nepaliTitle') is-invalid @enderror" required>@error('nepaliTitle')<div class="invalid-feedback">{{ $message }}</div>@enderror></div><label class="ltd-field-label" for="nepaliDescription">विवरण <span class="ltd-required">*</span></label><textarea id="nepaliDescription" name="nepaliDescription" rows="4" maxlength="1000" lang="ne" class="form-control @error('nepaliDescription') is-invalid @enderror" required>{{ old('nepaliDescription') }}</textarea>@error('nepaliDescription')<div class="invalid-feedback">{{ $message }}</div>@enderror></section>
        <section class="ltd-form-section"><label class="ltd-field-label" for="link">Related URL <span class="text-muted">(optional)</span></label><input id="link" type="url" name="link" value="{{ old('link') }}" maxlength="2048" class="form-control @error('link') is-invalid @enderror" placeholder="https://...">@error('link')<div class="invalid-feedback">{{ $message }}</div>@enderror></section>
    </div>
    <div class="ltd-form-actions"><a href="{{ route('allNotice') }}" class="btn btn-outline-secondary">Cancel</a><button class="btn btn-primary" type="submit" data-submit-button><i class="fas fa-plus mr-2"></i>Publish Notice</button></div>
</form></div>
@endsection
@section('page-script')@include('admin.crud.partials.add-form-script')@endsection
