@extends('admin.layout.master')
@section('title', 'Government Notice Imports')
@section('content')
<div class="ltd-page-header"><div><span class="ltd-page-header__eyebrow">Official Sources</span><h1>Government Notice Imports</h1></div><a href="{{ route('allNotice') }}" class="btn btn-outline-secondary">Back to Notices</a></div>
@if($errors->has('import'))<div class="alert alert-danger">{{ $errors->first('import') }}</div>@endif
<div class="ltd-panel mb-4"><div class="d-flex justify-content-between align-items-center flex-wrap"><div><h3 class="ltd-panel__title mb-1">Nepal Department of Transport Management</h3><p class="text-muted mb-0">Checks one official public page. New links always require review and enter Notices as drafts.</p></div><form method="POST" action="{{ route('governmentNotices.fetch') }}">@csrf<button class="btn btn-primary" type="submit"><i class="fas fa-sync-alt mr-2"></i>Check Official Website</button></form></div></div>
<div class="ltd-panel">
    @include('admin.crud.partials.table-controls', ['items' => $imports, 'sortOptions' => ['fetched_at' => 'Date fetched', 'title' => 'Title', 'status' => 'Review status', 'reviewed_at' => 'Review date', 'id' => 'ID'], 'filters' => ['status' => ['label' => 'Review status', 'options' => ['Pending' => 'Pending', 'Approved' => 'Approved', 'Rejected' => 'Rejected']]]])
    @if($imports->isEmpty())<div class="text-center py-5"><i class="fas fa-landmark fa-3x text-muted mb-3"></i><h4>No imported suggestions</h4><p class="text-muted mb-0">Check the official website to retrieve relevant driving-license links.</p></div>@else
    <div class="table-responsive"><table class="table table-hover"><thead><tr><th>Title</th><th>Source</th><th>Fetched</th><th>Status</th><th>Review</th></tr></thead><tbody>@foreach($imports as $import)<tr><td>{{ $import->title }}</td><td><a href="{{ $import->source_url }}" target="_blank" rel="noopener noreferrer">Open official page</a><div class="small text-muted">{{ $import->source_domain }}</div></td><td>{{ $import->fetched_at->format('M j, Y g:i A') }}</td><td><span class="badge badge-{{ $import->status === 'Pending' ? 'warning' : ($import->status === 'Approved' ? 'success' : 'secondary') }}">{{ $import->status }}</span></td><td>@if($import->status === 'Pending')<form method="POST" action="{{ route('governmentNotices.approve', $import->id) }}" class="d-inline">@csrf<button class="btn btn-sm btn-success" type="submit"><i class="fas fa-check mr-1"></i>Import as Draft</button></form><form method="POST" action="{{ route('governmentNotices.reject', $import->id) }}" class="d-inline">@csrf<button class="btn btn-sm btn-outline-danger" type="submit"><i class="fas fa-times mr-1"></i>Reject</button></form>@else<span class="text-muted small">{{ $import->reviewer?->name ?? 'System' }}<br>{{ $import->reviewed_at?->format('M j, Y') }}</span>@endif</td></tr>@endforeach</tbody></table></div>@include('admin.crud.partials.table-pagination', ['items' => $imports])
    @endif
</div>
@endsection
