@extends('learner.layout')
@section('title',__('Your journey starts here'))
@section('content')
<section class="hero"><div><p class="eyebrow">{{ __('YOUR ROAD TO CONFIDENCE') }}</p><h1>{{ __('Your next turn') }}<br>{{ __('starts here') }}<span class="accent">.</span></h1><p class="lead">{{ __('Get ready for Nepal’s driving licence exam. Learn the signs, practise the questions, and take your next step with confidence.') }}</p><div class="actions"><a class="button" href="{{ route('learn.practice') }}">{{ __('Start practising ↗') }}</a><a class="text-link" href="{{ route('learn.library.home') }}">{{ __('Browse the library →') }}</a></div><div class="stats"><div><strong>{{ $counts['questions'] }}</strong><span>{{ __('Practice questions') }}</span></div><div><strong>{{ $counts['signs'] }}</strong><span>{{ __('Traffic signs') }}</span></div><div><strong>{{ $counts['banks'] }}</strong><span>{{ __('Question banks') }}</span></div></div></div>
<div class="road-art" aria-hidden="true"><div class="art-label">{{ __('ONE STEP CLOSER') }}</div><svg viewBox="0 0 420 400"><path d="M210 430V290Q210 230 290 230T365 150Q365 80 285 80H180Q100 80 100 0" fill="none" stroke="#3B3B3B" stroke-width="90"/><path d="M210 430V290Q210 230 290 230T365 150Q365 80 285 80H180Q100 80 100 0" fill="none" stroke="#FFDE17" stroke-width="3" stroke-dasharray="14 13"/><circle cx="110" cy="280" r="46" fill="#FFDE17"/><path d="M110 307V253m-18 20 18-20 18 20" fill="none" stroke="#2a2a2a" stroke-width="6"/><circle cx="296" cy="329" r="12" fill="#FFDE17"/></svg><div class="art-note">{{ __('LEARN · PRACTISE · PROGRESS') }}</div></div></section>

<section class="section learning-journey"><div class="section-heading"><div><p class="eyebrow">{{ __('NOT SURE WHERE TO START?') }}</p><h2>{{ __('Your next three steps') }}</h2></div></div><div class="grid">
<a class="card" href="{{ route('learn.flashcards') }}"><span class="badge">{{ __('01 · RECOGNISE') }}</span><h3>{{ __('Turn signs into second nature.') }}</h3><p>{{ __('Test your memory with traffic sign flashcards. Guess first, then reveal the meaning.') }}</p><span class="text-link">{{ __('Try flashcards →') }}</span></a>
<a class="card" href="{{ route('learn.library','question-bank') }}"><span class="badge">{{ __('02 · UNDERSTAND') }}</span><h3>{{ __('Get familiar with the questions.') }}</h3><p>{{ __('Explore question-bank documents in English or Nepali, at your own pace.') }}</p><span class="text-link">{{ __('Open question banks →') }}</span></a>
<a class="card" href="{{ route('learn.practice') }}"><span class="badge">{{ __('03 · PUT IT INTO PRACTICE') }}</span><h3>{{ __('Learn from every attempt.') }}</h3><p>{{ __('Answer a few questions, check your results, and review the explanations.') }}</p><span class="text-link">{{ __('Start practising →') }}</span></a>
</div></section>
@endsection