@extends('learner.layout')
@section('title',__('My revision modules'))
@section('content')
<div class="page-heading"><a href="{{ route('learn.premium') }}">{{ __('← Premium') }}</a><p class="eyebrow">{{ __('TURN MISTAKES INTO PROGRESS') }}</p><h1>{{ __('My revision modules') }}</h1><p class="lead">{{ __('Review the questions you last answered incorrectly, then try them again.') }}</p><p class="muted">{{ __('Based on your latest 100 completed sessions. Updated or unpublished questions are excluded. A correct retry clears that question from this list.') }}</p></div>
@if($modules->isNotEmpty())
<section class="card revision-module"><span class="badge">{{ __('BUILT FROM YOUR RESULTS') }}</span><h2>{{ __('Your personalized practice set') }}</h2><p>{{ __('Mix questions you missed with other published questions from the same topics. This checks your understanding beyond memorizing previous answers.') }}</p><form class="filters" action="{{ route('learn.practice.start') }}" method="post">@csrf<input type="hidden" name="mode" value="personalized"><label>{{ __('Focus') }}<select name="category"><option value="">{{ __('All topics to improve') }}</option>@foreach($modules as $topic=>$items)<option value="{{ $topic }}">{{ $topic }} ({{ $items->count() }} {{ __('to revisit)') }}</option>@endforeach</select></label>@include('learner.practice-language')<label>{{ __('Questions') }}<select name="count"><option value="5">{{ __('5 questions') }}</option><option value="10">{{ __('10 questions') }}</option><option value="20">{{ __('20 questions') }}</option></select></label><button class="button">{{ __('Build my practice set') }}</button></form><p class="muted">{{ __('Up to half the set starts with missed questions. Related questions fill the rest where available; smaller banks produce shorter sets. Only published questions are scored.') }}</p></section>
@endif
@forelse($modules as $category=>$questions)<section class="card revision-module"><div class="section-heading"><h2>{{ __($category) }}</h2><span class="badge">{{ $questions->count() }} {{ __('to revisit') }}</span></div>
@foreach($questions as $question)<details class="settings-detail"><summary>{{ $loop->iteration }}. {{ $question->question }}</summary>
@if($question->image_url)<img class="content-image" src="{{ $question->image_url }}" alt="{{ __('Question illustration') }}">@endif
<p class="prose"><strong>{{ __('Correct answer:') }} {{ $question->correctOption }}</strong> — {{ $question->{'option'.(['A'=>1,'B'=>2,'C'=>3,'D'=>4][$question->correctOption])} }}</p>
@if($question->explanation)<p class="prose">{{ $question->explanation }}</p>@else<p class="muted">{{ __('An explanation has not been added for this question yet.') }}</p>@endif
<p><a class="button secondary" href="{{ route('learn.premium.chat',['question_id'=>$question->id]) }}">{{ __('Explain with Gemini →') }}</a></p><a class="report-link" href="{{ route('learn.report',['question',$question->id]) }}">{{ __('Report an issue with this solution') }}</a></details>@endforeach
<form action="{{ route('learn.practice.start') }}" method="post" class="actions">@csrf<input type="hidden" name="mode" value="revision"><input type="hidden" name="category" value="{{ $category }}"><input type="hidden" name="count" value="20"><button class="button">{{ __('Retry this topic →') }}</button><span class="muted">{{ __('Up to 20 questions per session') }}</span></form></section>
@empty<div class="empty"><h2>{{ __('No questions to revisit right now.') }}</h2><p>{{ __('Complete a practice session to find topics worth revisiting. If you have already practised, your latest answers may all be correct or the content may have changed.') }}</p><a class="button" href="{{ route('learn.practice') }}">{{ __('Start practice →') }}</a></div>@endforelse
@endsection
