<section class="card settings-card" id="sign-in-options"><div class="settings-section-heading"><span class="badge">{{ __('CONNECTED ACCOUNTS') }}</span><h2>{{ __('Sign in with Google') }}</h2><p>{{ __('Use Google as an alternative to your email and password.') }}</p></div>
@if($user->google_id)<span class="badge">{{ __('Google connected') }}</span><form class="stack" method="post" action="{{ route('learn.google.disconnect') }}">@csrf @method('DELETE')<label>{{ __('Current password') }}<input type="password" name="current_password" required autocomplete="current-password"></label><button class="button secondary">{{ __('Disconnect Google') }}</button></form>
@elseif(config('services.google.client_id') && config('services.google.client_secret') && config('services.google.redirect'))<form class="stack" method="post" action="{{ route('learn.google.connect') }}">@csrf<label>{{ __('Confirm your password') }}<input type="password" name="current_password" required autocomplete="current-password"></label><button class="button secondary">{{ __('Connect Google') }}</button></form>
@else<p class="muted">{{ __('Google sign-in is not available yet. You can continue using your email and password.') }}</p>@endif
</section>
<section class="card settings-card" id="two-step-verification"><div class="settings-section-heading"><span class="badge">{{ __('EXTRA SECURITY') }}</span><h2>{{ __('Two-step verification') }}</h2><p>{{ __('Add a code from Google Authenticator, Microsoft Authenticator, or another compatible app when you sign in.') }}</p></div>
@if(session('recovery_codes'))<div class="alert"><strong>{{ __('Save these recovery codes somewhere safe.') }}</strong><p>{{ __('Each code works once if you lose access to your authenticator. They will not be displayed again.') }}</p><ul>@foreach(session('recovery_codes') as $code)<li><code>{{ $code }}</code></li>@endforeach</ul></div>@endif
@if($user->mfa_secret)<span class="badge">{{ __('MFA enabled') }}</span><p class="field-help">{{ count($user->mfa_recovery_codes ?? []) }} {{ __('recovery codes remaining. To replace your authenticator or recovery codes, disable MFA and set it up again.') }}</p><details><summary>{{ __('Turn off two-step verification') }}</summary><form class="stack" method="post" action="{{ route('learn.mfa.disable') }}">@csrf @method('DELETE')<label>{{ __('Current password') }}<input type="password" name="current_password" required autocomplete="current-password"></label><label>{{ __('Authenticator or recovery code') }}<input name="code" required maxlength="64" autocomplete="one-time-code"></label><button class="button secondary">{{ __('Disable MFA') }}</button></form></details>
@elseif(($setup=session('mfa_setup')) && $setup['user']===$user->id && $setup['expires']>=time())
<ol><li>{{ __('Open your authenticator app and add a new account using a setup key.') }}</li><li>{{ __('Choose a time-based code and paste this key:') }} <code class="mfa-setup-key">{{ $setup['secret'] }}</code></li><li>{{ __('Name the entry Learn to Drive (') }}{{ $user->email }}{{ __('), then enter the code below.') }}</li></ol><p class="field-help">{{ __('This setup expires after 10 minutes. Never share the setup key.') }}</p><form class="stack" method="post" action="{{ route('learn.mfa.enable') }}">@csrf<label>{{ __('Six-digit code') }}<input name="code" required pattern="[0-9]{6}" maxlength="6" inputmode="numeric" autocomplete="one-time-code"></label><button class="button">{{ __('Enable MFA') }}</button></form>
@else<p>{{ __('Optional. You will receive recovery codes when you enable it. Enabling MFA also signs out existing app tokens; MFA-protected accounts currently sign in through the website.') }}</p><form class="stack" method="post" action="{{ route('learn.mfa.setup') }}">@csrf<label>{{ __('Confirm your password') }}<input type="password" name="current_password" required autocomplete="current-password"></label><button class="button">{{ __('Set up authenticator') }}</button></form>@endif
</section>
