@extends('admin.layout.master')
@section('title', 'Add Exam Paper')
@section('content')
<div class="ltd-page-header"><div><span class="ltd-page-header__eyebrow">Study Materials</span><h1>Add Exam Paper</h1></div></div>
<div class="ltd-form-shell"><form class="ltd-form-card" action="{{ route('insertExamPaper') }}" method="POST" enctype="multipart/form-data" data-add-form>@csrf
    <div class="ltd-form-card__intro"><i class="fas fa-file-alt"></i><div><h2>Upload a bilingual exam paper</h2><p>Use matching English and Nepali PDFs so learners can choose their preferred language.</p></div></div>
    <div class="ltd-form-card__body">
        <section class="ltd-form-section"><h3 class="ltd-form-section__title">Paper details</h3><div class="row"><div class="col-md-6 form-group"><label class="ltd-field-label" for="name">English name <span class="ltd-required">*</span></label><input id="name" name="name" value="{{ old('name') }}" maxlength="255" class="form-control @error('name') is-invalid @enderror" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6 form-group"><label class="ltd-field-label" for="nepaliName">Nepali name <span class="ltd-required">*</span></label><input id="nepaliName" name="nepaliName" value="{{ old('nepaliName') }}" maxlength="255" lang="ne" class="form-control @error('nepaliName') is-invalid @enderror" required>@error('nepaliName')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div><label class="ltd-field-label" for="description">Description <span class="ltd-required">*</span></label><textarea id="description" name="description" rows="4" maxlength="1000" class="form-control @error('description') is-invalid @enderror" required>{{ old('description') }}</textarea>@error('description')<div class="invalid-feedback">{{ $message }}</div>@enderror></section>
        <section class="ltd-form-section"><h3 class="ltd-form-section__title">PDF files</h3><div class="row"><div class="col-md-6 form-group"><div class="ltd-file-field"><label class="ltd-field-label" for="englishFile">English PDF <span class="ltd-required">*</span></label><input id="englishFile" type="file" name="englishFile" accept=".pdf,application/pdf" class="form-control-file @error('englishFile') is-invalid @enderror" required>@error('englishFile')<div class="text-danger small mt-2">{{ $message }}</div>@enderror<span class="ltd-field-help">PDF, maximum 10 MB.</span></div></div><div class="col-md-6 form-group"><div class="ltd-file-field"><label class="ltd-field-label" for="nepaliFile">Nepali PDF <span class="ltd-required">*</span></label><input id="nepaliFile" type="file" name="nepaliFile" accept=".pdf,application/pdf" class="form-control-file @error('nepaliFile') is-invalid @enderror" required>@error('nepaliFile')<div class="text-danger small mt-2">{{ $message }}</div>@enderror<span class="ltd-field-help">PDF, maximum 10 MB.</span></div></div></div></section>
    </div>
    <div class="ltd-form-actions"><a href="{{ route('allExamPaper') }}" class="btn btn-outline-secondary">Cancel</a><button class="btn btn-primary" type="submit" data-submit-button><i class="fas fa-plus mr-2"></i>Add Exam Paper</button></div>
</form></div>
@endsection
@section('page-script')@include('admin.crud.partials.add-form-script')@endsection
